name = "FenicsPy"
uuid = "3efbc270-88d0-4c7e-ad96-7b69f887f208"
authors = ["chaoskey <chaoskey@gmail.com>"]
version = "0.2.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[compat]
PyCall = "1.9"
PyPlot = "2.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"

[targets]
test = ["Test", "SymPy"]



